name: Manual build API example

on:
  pull_request:
    paths:
      - ".github/workflows/example-build.yml"
      - "examples/**"
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  local-ci:
    name: Example app
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Start containers
        run: docker compose up -d --build
        working-directory: "./examples/booking"

      - uses: schemathesis/action@806cace2053cbbac93188e1281ff7da415643160 # v3.0.0
        with:
          schema: "http://127.0.0.1:8080/openapi.json"
          authorization: "Bearer secret-token"
          max-examples: "10"
          wait-for-schema: "30"
          args: "--report junit"

      - name: Upload test results
        uses: actions/upload-artifact@4.6.0
        if: always()
        with:
          name: schemathesis-results
          path: schemathesis-report/

      - name: Stop containers
        if: always()
        run: docker compose down
        working-directory: "./examples/booking"
